//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordGenerator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;hasma&apos; application is a password manager that securely stores and manages user passwords. It offers features such as strong password generation, organizing accounts into categories, and quick logins to various portals..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is my first larger C# project. It took more than 30 hours to create. If you know how to improve my code, please file issues on GitHub..
        /// </summary>
        public static string AboutExtra {
            get {
                return ResourceManager.GetString("AboutExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.0 | © 2026 Qwaterek.
        /// </summary>
        public static string AboutFooter {
            get {
                return ResourceManager.GetString("AboutFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GitHub profile.
        /// </summary>
        public static string AboutGitHubTooltip {
            get {
                return ResourceManager.GetString("AboutGitHubTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        public static string AccountPanel_AddButton {
            get {
                return ResourceManager.GetString("AccountPanel_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new account to the database.
        /// </summary>
        public static string AccountPanel_AddButtonTooltip {
            get {
                return ResourceManager.GetString("AccountPanel_AddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AccountPanel_EmailHeader {
            get {
                return ResourceManager.GetString("AccountPanel_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AccountPanel_PasswordHeader {
            get {
                return ResourceManager.GetString("AccountPanel_PasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL / Service.
        /// </summary>
        public static string AccountPanel_UrlHeader {
            get {
                return ResourceManager.GetString("AccountPanel_UrlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string AccountPanel_UserHeader {
            get {
                return ResourceManager.GetString("AccountPanel_UserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasma - Password Manager.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current master password.
        /// </summary>
        public static string ChangeMasterPwd_CurrentHeader {
            get {
                return ResourceManager.GetString("ChangeMasterPwd_CurrentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current master password to continue..
        /// </summary>
        public static string ChangeMasterPwd_CurrentSubHeader {
            get {
                return ResourceManager.GetString("ChangeMasterPwd_CurrentSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password changed successfully..
        /// </summary>
        public static string ChangeMasterPwd_Success {
            get {
                return ResourceManager.GetString("ChangeMasterPwd_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect current password. Master password was not changed..
        /// </summary>
        public static string ChangeMasterPwd_WrongCurrent {
            get {
                return ResourceManager.GetString("ChangeMasterPwd_WrongCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ColEmail {
            get {
                return ResourceManager.GetString("ColEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ColPassword {
            get {
                return ResourceManager.GetString("ColPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string ColUrl {
            get {
                return ResourceManager.GetString("ColUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string ColUser {
            get {
                return ResourceManager.GetString("ColUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied {0}.
        /// </summary>
        public static string CopiedMessage {
            get {
                return ResourceManager.GetString("CopiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Account.
        /// </summary>
        public static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string CreateEmailLabel {
            get {
                return ResourceManager.GetString("CreateEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use quick password generator.
        /// </summary>
        public static string CreateFastPassword {
            get {
                return ResourceManager.GetString("CreateFastPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a quick password generator which is weaker but easier to remember.
        /// </summary>
        public static string CreateFastPasswordTooltip {
            get {
                return ResourceManager.GetString("CreateFastPasswordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string CreatePasswordLabel {
            get {
                return ResourceManager.GetString("CreatePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        public static string CreateUrlLabel {
            get {
                return ResourceManager.GetString("CreateUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string CreateUsernameLabel {
            get {
                return ResourceManager.GetString("CreateUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this account?.
        /// </summary>
        public static string DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        public static string EditAccountTitle {
            get {
                return ResourceManager.GetString("EditAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export file password.
        /// </summary>
        public static string ExportPwd_Header {
            get {
                return ResourceManager.GetString("ExportPwd_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a password to encrypt the exported file. You&apos;ll need it to import on another device - remember it..
        /// </summary>
        public static string ExportPwd_SubHeader {
            get {
                return ResourceManager.GetString("ExportPwd_SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file has been saved and encrypted with the given password.
        ///
        ///REMEMBER: without this password the data in the file cannot be recovered - it is not stored anywhere..
        /// </summary>
        public static string ExportPwd_SuccessMsg {
            get {
                return ResourceManager.GetString("ExportPwd_SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click with the left mouse button to copy.
        /// </summary>
        public static string FastPwd_CopyHint {
            get {
                return ResourceManager.GetString("FastPwd_CopyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Fast Password.
        /// </summary>
        public static string FastPwd_HeaderLabel {
            get {
                return ResourceManager.GetString("FastPwd_HeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of characters:.
        /// </summary>
        public static string FastPwd_LengthLabel {
            get {
                return ResourceManager.GetString("FastPwd_LengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a new account with the generated password.
        /// </summary>
        public static string FastPwd_SaveTooltip {
            get {
                return ResourceManager.GetString("FastPwd_SaveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate password.
        /// </summary>
        public static string GeneratePassword {
            get {
                return ResourceManager.GetString("GeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the file - wrong password or the file is corrupted..
        /// </summary>
        public static string ImportPwd_FailMsg {
            get {
                return ResourceManager.GetString("ImportPwd_FailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file password.
        /// </summary>
        public static string ImportPwd_Header {
            get {
                return ResourceManager.GetString("ImportPwd_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password used to encrypt this configuration file..
        /// </summary>
        public static string ImportPwd_SubHeader {
            get {
                return ResourceManager.GetString("ImportPwd_SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported {0} accounts and saved them to accounts.json!.
        /// </summary>
        public static string ImportPwd_SuccessMsg {
            get {
                return ResourceManager.GetString("ImportPwd_SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string LangPolish {
            get {
                return ResourceManager.GetString("LangPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was last modified on:.
        /// </summary>
        public static string LastModifiedText {
            get {
                return ResourceManager.GetString("LastModifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was last modified on: {0}.
        /// </summary>
        public static string LastModifiedWithDate {
            get {
                return ResourceManager.GetString("LastModifiedWithDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set new master password.
        /// </summary>
        public static string MasterPwd_ChangeHeader {
            get {
                return ResourceManager.GetString("MasterPwd_ChangeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new master password. It will replace your current one..
        /// </summary>
        public static string MasterPwd_ChangeSubHeader {
            get {
                return ResourceManager.GetString("MasterPwd_ChangeSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close program.
        /// </summary>
        public static string MasterPwd_CloseButton {
            get {
                return ResourceManager.GetString("MasterPwd_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat master password:.
        /// </summary>
        public static string MasterPwd_ConfirmLabel {
            get {
                return ResourceManager.GetString("MasterPwd_ConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        public static string MasterPwd_Err_Empty {
            get {
                return ResourceManager.GetString("MasterPwd_Err_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match..
        /// </summary>
        public static string MasterPwd_Err_Mismatch {
            get {
                return ResourceManager.GetString("MasterPwd_Err_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password should be at least 4 characters..
        /// </summary>
        public static string MasterPwd_Err_TooShort {
            get {
                return ResourceManager.GetString("MasterPwd_Err_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string MasterPwd_Err_Wrong {
            get {
                return ResourceManager.GetString("MasterPwd_Err_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password:.
        /// </summary>
        public static string MasterPwd_Label {
            get {
                return ResourceManager.GetString("MasterPwd_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set master password.
        /// </summary>
        public static string MasterPwd_NewHeader {
            get {
                return ResourceManager.GetString("MasterPwd_NewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password will protect all your saved accounts and passwords. Remember it well - it cannot be recovered..
        /// </summary>
        public static string MasterPwd_NewSubHeader {
            get {
                return ResourceManager.GetString("MasterPwd_NewSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter master password.
        /// </summary>
        public static string MasterPwd_UnlockHeader {
            get {
                return ResourceManager.GetString("MasterPwd_UnlockHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your master password to unlock your saved accounts..
        /// </summary>
        public static string MasterPwd_UnlockSubHeader {
            get {
                return ResourceManager.GetString("MasterPwd_UnlockSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Password.
        /// </summary>
        public static string MasterPwd_WindowTitle {
            get {
                return ResourceManager.GetString("MasterPwd_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium password contains a mix of letters and digits.
        /// </summary>
        public static string MediumTooltip {
            get {
                return ResourceManager.GetString("MediumTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Program.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string MenuAccounts {
            get {
                return ResourceManager.GetString("MenuAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Account.
        /// </summary>
        public static string MenuAddAccount {
            get {
                return ResourceManager.GetString("MenuAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Master Password.
        /// </summary>
        public static string MenuChangeMasterPassword {
            get {
                return ResourceManager.GetString("MenuChangeMasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Fast Password.
        /// </summary>
        public static string MenuFastPassword {
            get {
                return ResourceManager.GetString("MenuFastPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Configuration File.
        /// </summary>
        public static string MenuLoadConfig {
            get {
                return ResourceManager.GetString("MenuLoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into All Portals.
        /// </summary>
        public static string MenuLoginAll {
            get {
                return ResourceManager.GetString("MenuLoginAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Configuration File.
        /// </summary>
        public static string MenuSaveConfig {
            get {
                return ResourceManager.GetString("MenuSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts.
        /// </summary>
        public static string MenuShortcuts {
            get {
                return ResourceManager.GetString("MenuShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! Exported config contains an UNENCRYPTED KEY. Delete it immediately after import!.
        /// </summary>
        public static string MsgConfigWarnText {
            get {
                return ResourceManager.GetString("MsgConfigWarnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Warning.
        /// </summary>
        public static string MsgConfigWarnTitle {
            get {
                return ResourceManager.GetString("MsgConfigWarnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish Word Generator.
        /// </summary>
        public static string PolishGenNote {
            get {
                return ResourceManager.GetString("PolishGenNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password:.
        /// </summary>
        public static string PwdPrompt_ConfirmLabel {
            get {
                return ResourceManager.GetString("PwdPrompt_ConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        public static string PwdPrompt_Err_Empty {
            get {
                return ResourceManager.GetString("PwdPrompt_Err_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match..
        /// </summary>
        public static string PwdPrompt_Err_Mismatch {
            get {
                return ResourceManager.GetString("PwdPrompt_Err_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be at least 6 characters..
        /// </summary>
        public static string PwdPrompt_Err_TooShort {
            get {
                return ResourceManager.GetString("PwdPrompt_Err_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PwdPrompt_Label {
            get {
                return ResourceManager.GetString("PwdPrompt_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string PwdPrompt_OkButton {
            get {
                return ResourceManager.GetString("PwdPrompt_OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new password.
        /// </summary>
        public static string RefreshPasswordTooltip {
            get {
                return ResourceManager.GetString("RefreshPasswordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new account (opens Add Account window).
        /// </summary>
        public static string Shortcut_AddAccount_Desc {
            get {
                return ResourceManager.GetString("Shortcut_AddAccount_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+N.
        /// </summary>
        public static string Shortcut_AddAccount_Shortcut {
            get {
                return ResourceManager.GetString("Shortcut_AddAccount_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy to clipboard (email, username, password) .
        /// </summary>
        public static string Shortcut_CopyToClipboard_Desc {
            get {
                return ResourceManager.GetString("Shortcut_CopyToClipboard_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double left-click.
        /// </summary>
        public static string Shortcut_CopyToClipboard_Shortcut {
            get {
                return ResourceManager.GetString("Shortcut_CopyToClipboard_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open quick password generator.
        /// </summary>
        public static string Shortcut_FastPassword_Desc {
            get {
                return ResourceManager.GetString("Shortcut_FastPassword_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4.
        /// </summary>
        public static string Shortcut_FastPassword_Shortcut {
            get {
                return ResourceManager.GetString("Shortcut_FastPassword_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus search box (if not focused) and select text.
        /// </summary>
        public static string Shortcut_FocusSearch_Desc {
            get {
                return ResourceManager.GetString("Shortcut_FocusSearch_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Shortcut_FocusSearch_Shortcut {
            get {
                return ResourceManager.GetString("Shortcut_FocusSearch_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load configuration from file.
        /// </summary>
        public static string Shortcut_LoadConfig_Desc {
            get {
                return ResourceManager.GetString("Shortcut_LoadConfig_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+F6.
        /// </summary>
        public static string Shortcut_LoadConfig_Shortcut {
            get {
                return ResourceManager.GetString("Shortcut_LoadConfig_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into all saved portals.
        /// </summary>
        public static string Shortcut_LoginAll_Desc {
            get {
                return ResourceManager.GetString("Shortcut_LoginAll_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+L.
        /// </summary>
        public static string Shortcut_LoginAll_Shortcut {
            get {
                return ResourceManager.GetString("Shortcut_LoginAll_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open accounts panel.
        /// </summary>
        public static string Shortcut_OpenAccounts_Desc {
            get {
                return ResourceManager.GetString("Shortcut_OpenAccounts_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3.
        /// </summary>
        public static string Shortcut_OpenAccounts_Shortcut {
            get {
                return ResourceManager.GetString("Shortcut_OpenAccounts_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reveal the password.
        /// </summary>
        public static string Shortcut_RevealPassword_Desc {
            get {
                return ResourceManager.GetString("Shortcut_RevealPassword_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold right-click (password).
        /// </summary>
        public static string Shortcut_RevealPassword_Shortcut {
            get {
                return ResourceManager.GetString("Shortcut_RevealPassword_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration to file (exports unencrypted key).
        /// </summary>
        public static string Shortcut_SaveConfig_Desc {
            get {
                return ResourceManager.GetString("Shortcut_SaveConfig_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+F5.
        /// </summary>
        public static string Shortcut_SaveConfig_Shortcut {
            get {
                return ResourceManager.GetString("Shortcut_SaveConfig_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the list of keyboard shortcuts.
        /// </summary>
        public static string Shortcut_ShowShortcuts_Desc {
            get {
                return ResourceManager.GetString("Shortcut_ShowShortcuts_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        public static string Shortcut_ShowShortcuts_Shortcut {
            get {
                return ResourceManager.GetString("Shortcut_ShowShortcuts_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Shortcuts_ColDescription {
            get {
                return ResourceManager.GetString("Shortcuts_ColDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string Shortcuts_ColShortcut {
            get {
                return ResourceManager.GetString("Shortcuts_ColShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: You can change language in Help -&gt; Language.
        /// </summary>
        public static string Shortcuts_Footer {
            get {
                return ResourceManager.GetString("Shortcuts_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts.
        /// </summary>
        public static string Shortcuts_Header {
            get {
                return ResourceManager.GetString("Shortcuts_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below are some useful keyboard shortcuts you can use in the application..
        /// </summary>
        public static string Shortcuts_Intro {
            get {
                return ResourceManager.GetString("Shortcuts_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        public static string Strong {
            get {
                return ResourceManager.GetString("Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong password contains a mix of letters, digits and special characters.
        /// </summary>
        public static string StrongTooltip {
            get {
                return ResourceManager.GetString("StrongTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in at least the username and password..
        /// </summary>
        public static string ValidationRequiredFields {
            get {
                return ResourceManager.GetString("ValidationRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        public static string Weak {
            get {
                return ResourceManager.GetString("Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak password contains only letters or digits.
        /// </summary>
        public static string WeakTooltip {
            get {
                return ResourceManager.GetString("WeakTooltip", resourceCulture);
            }
        }
    }
}
